[build]
builder = "dockerfile"
dockerfilePath = "apps/seller/Dockerfile"

[deploy]
startCommand = "npm start --workspace=@waw/seller"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
