[build]
builder = "dockerfile"
dockerfilePath = "apps/admin/Dockerfile"

[deploy]
startCommand = "npm start --workspace=@waw/admin"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
